language: java

services:
  - docker

jdk:
- openjdk10

before_install:
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar

script:
- ./gradlew build integrationTest jar
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . -t quest-command:dev .
- docker tag quest-command:dev quest-command:latest

deploy:
- provider: script
  skip_cleanup: true
  script: docker push manapart/quest-command:dev
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: docker push manapart/quest-command:latest
  on:
    branch: release
- provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  name: $NAME
  on:
    branch: release