language: java

services:
  - docker

jdk:
- openjdk11

before_install:
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar

script:
- ./gradlew build buildData test test-integration jar
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build . -t manapart/quest-command:dev
- docker tag manapart/quest-command:dev manapart/quest-command:stable

deploy:
- provider: script
  skip_cleanup: true
  script: docker push manapart/quest-command:dev
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: docker push manapart/quest-command:stable
  on:
    branch: release
- provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  name: $NAME
  on:
    branch: release
