name: Deploy Docker Latest

on:
  push:
    branches:
#      - 'master'
#      - 'release'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build jar
      - name: Docker Build
        run: docker build . -t manapart/quest-command:dev
      - name: Docker Tag
        run: docker tag manapart/quest-command:dev manapart/quest-command:stable
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push Dev
        if: contains(github.ref, "master")
        run: docker push manapart/quest-command:dev
#      - name: Docker Push Stable
#        if: ${GITHUB_REF##*/} == "release"
#        run: docker push manapart/quest-command:stable
#      - name: Docker Don't Push
#        if: ${GITHUB_REF##*/} != "release" && ${GITHUB_REF##*/} != "master"
#        run: echo "Skipping push on ${GITHUB_REF##*/}"
